version: '3.8'

services:
  api1:
    build: ./api1
    container_name: api1_container
    ports:
      - "8000:8000"
    environment:
      # URL ของ API 2 ที่ API 1 จะเรียกใช้
      # ใช้ชื่อ service ใน Docker Compose ("api2") เพื่อให้ Docker จัดการ DNS resolution ให้
      API2_URL: http://api2:8001/api2-process # <<< ตรวจสอบตรงนี้: URL และ Endpoint ที่ถูกต้องของ API 2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api2:
    build: ./api2
    container_name: api2_container
    ports:
      - "8001:8001"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"